import { relations } from "drizzle-orm"
import { boolean, text, timestamp } from "drizzle-orm/pg-core"
import {integer,varchar,pgTable} from "drizzle-orm/pg-core"
// use text if you really don't want any troubles later one but these fields shouldn't be that long
export const users = pgTable("users",{
    id:integer().generatedAlwaysAsIdentity().primaryKey(),
    email:varchar({length:255}).notNull().unique(),
    name:varchar({length:255}),
    username:varchar({length:255}).notNull().unique(),
    password:varchar({length:255}).notNull()
})
// Relations..user can have one token and one subscription field
export const usersRelations = relations(users,({one, many}) => ({
    token:one(tokens),
    subscriptions:one(subscriptions),
    posts:many(posts)
}))

// tokens are numbers generated by a fun i made
export const tokens = pgTable("tokens",{
    id:integer().primaryKey().generatedAlwaysAsIdentity(),
    token:integer().unique(),
    user:integer().references(() => users.id,{onDelete:"cascade"}).unique()
})
//
export const tokensRelations = relations(tokens,({one}) => ({
    user:one(users, {fields: [tokens.user], references : [users.id]})
}))

export const subscriptions = pgTable("subscriptions" , {
    id:integer().primaryKey().generatedAlwaysAsIdentity(),
    premium:boolean().notNull().default(false),
    user:integer().references(() => users.id,{onDelete:"cascade"}).unique()
})

export const subscriptionsRelations = relations(subscriptions,({one}) => ({
    user:one(users ,{fields: [subscriptions.user], references : [users.id]})
}))

// Posts table for user posts/history
export const posts = pgTable("posts", {
    id:integer().primaryKey().generatedAlwaysAsIdentity(),
    title:varchar({length:255}).notNull(),
    content:text().notNull(),
    userId:integer().references(() => users.id, {onDelete: "cascade"}).notNull(),
    createdAt:timestamp().defaultNow().notNull(),
    updatedAt:timestamp().defaultNow().notNull()
})

export const postsRelations = relations(posts, ({one}) => ({
    user: one(users, {
        fields: [posts.userId],
        references: [users.id]
    })
}))